name: imgref
channels:
  - pytorch
  - defaults
dependencies:
  - cudatoolkit=10.0.130
  - future=0.17.1
  - git-lfs=2.6.1
  - joblib=0.13.2
  - matplotlib=3.1.0
  - numpy=1.16.4
  - pandas=0.25.1
  - pillow=6.1.0
  - pip=19.1.1
  - python=3.7.3
  - pytorch=1.1.0
  - scipy=1.3.1
  - scikit-learn=0.21.3
  - torchvision=0.3.0
  - pip:
    - pyitlib==0.2.2
